# -*- coding: utf-8 -*-
"""new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-TIDbUOizPVxFnaTY-BbydeXD-mOzU8
"""

# -*- coding: utf-8 -*-
"""copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sE4yi2V3lnoR9QXUUirhoKz9nD9FN6hB
"""

import random
import itertools
from copy import deepcopy

#============================================
# 1. TEAMS — POT 1
# ============================================
teams_pot1_original = [
    {"name": "🇧🇷Brazil",      "continent": ["CONMEBOL"]},
    {"name": "🇺🇸USA",         "continent": ["CONCACAF"]},
     {"name": "🇫🇷France",      "continent": ["UEFA"]},
     {"name": "🇪🇸Spain",       "continent": ["UEFA"]},
     {"name": "🇨🇦Canada",      "continent": ["CONCACAF"]},
     {"name": "🇲🇽Mexico",      "continent": ["CONCACAF"]},
     {"name": "🇦🇷Argentina",   "continent": ["CONMEBOL"]},
     {"name": "🏴󠁧󠁢󠁥󠁮󠁧󠁿England",     "continent": ["UEFA"]},
     {"name": "🇧🇪Belgium",     "continent": ["UEFA"]},
     {"name": "🇳🇱Netherlands", "continent": ["UEFA"]},
     {"name": "🇩🇪Germany",     "continent": ["UEFA"]},
     {"name": "🇵🇹Portugal",    "continent": ["UEFA"]}
]

# ============================================
# 2. TEAMS — POT 2
# ============================================
teams_pot2_original = [
    {"name": "🇨🇴Colombia",    "continent": ["CONMEBOL"]},
    {"name": "🇯🇵Japan",       "continent": ["AFC"]},
     {"name": "🇨🇭Switzerland", "continent": ["UEFA"]},
     {"name": "🇲🇦Morocco",     "continent": ["CAF"]},
     {"name": "🇺🇾Uruguay",     "continent": ["CONMEBOL"]},
     {"name": "🇪🇨Ecuador",     "continent": ["CONMEBOL"]},
     {"name": "🇮🇷Iran",        "continent": ["AFC"]},
     {"name": "🇰🇷South Korea", "continent": ["AFC"]},
     {"name": "🇦🇺Australia",   "continent": ["AFC"]},
     {"name": "🇦🇹Austria",     "continent": ["UEFA"]},
     {"name": "🇭🇷Croatia",     "continent": ["UEFA"]},
     {"name": "🇸🇳Senegal",     "continent": ["CAF"]}
]

# ============================================
# 3. TEAMS — POT 3
# ============================================
teams_pot3_original = [
    {"name": "🇶🇦Qatar",        "continent": ["AFC"]},
    {"name": "🇺🇿Uzbekistan",   "continent": ["AFC"]},
    {"name": "🇳🇴Norway",       "continent": ["UEFA"]},
    {"name": "🇩🇿Algeria",      "continent": ["CAF"]},
    {"name": "🇸🇦Saudi Arabia", "continent": ["AFC"]},
    {"name": "🇪🇬Egypt",        "continent": ["CAF"]},
    {"name": "🇨🇮Ivory Coast",  "continent": ["CAF"]},
    {"name": "🇹🇳Tunisia",      "continent": ["CAF"]},
    {"name": "🇿🇦South Africa", "continent": ["CAF"]},
    {"name": "🇵🇾Paraguay",     "continent": ["CONMEBOL"]},
    {"name": "🇵🇦Panama",       "continent": ["CONCACAF"]},
    {"name": "🏴󠁧󠁢󠁳󠁣󠁴󠁿Scotland",     "continent": ["UEFA"]}
]

# ============================================
# 4. TEAMS — POT 4
# ============================================
teams_pot4_original = [
    {"name": "🇭🇹Haiti",       "continent": ["CONCACAF"]},
    {"name": "🇨🇼Curacao",     "continent": ["CONCACAF"]},
    # {"name": "DR Congo/Jamaica/New Caledonia", "continent": ["CAF", "CONCACAF", "OFC"]},
    # {"name": "Iraq/Bolivia/Suriname",          "continent": ["AFC"]},
    {"name": "🇯🇴Jordan",      "continent": ["AFC"]},
    {"name": "🇳🇿New Zealand", "continent": ["OFC"]},
    {"name": "🇬🇭Ghana",       "continent": ["CAF"]},
    {"name": "🇨🇻Cape Verde",  "continent": ["CAF"]},
    {"name": "🇮🇹Italy/🏴󠁧󠁢󠁷󠁬󠁳󠁿Wales/🇧🇦Bosnia and Herzegovina/🇬🇧Northern Ireland", "continent": ["UEFA"]},
    {"name": "🇺🇦Ukraine/🇵🇱Poland/🇦🇱Albania/🇸🇪Sweden",                       "continent": ["UEFA"]},
    {"name": "🇹🇷Turkey/🇸🇰Slovakia/🇽🇰Kosovo/🇷🇴Romania",                      "continent": ["UEFA"]},
    {"name": "🇩🇰Denmark/🇨🇿Czech Republic/🇮🇪Ireland/🇲🇰North Macedonia",      "continent": ["UEFA"]}
]

# ============================================
# 5. GROUP TEMPLATE (12 GROUPS, EACH MUST HAVE 4 TEAMS)
# ============================================
groups_original = [
    {'label': 1, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 2, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 3, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 4, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 5, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 6, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 7, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 8, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 9, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 10, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 11, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1},
    {'label': 12, 'teams': [None, None, None, None], 'UEFA': 2, 'AFC': 1, 'CAF': 1, 'CONCACAF': 1, 'CONMEBOL': 1, 'OFC': 1}
]
#test
# print(groups)

# ============================================
# 6. FUNCTION — COUNT CONTINENTS ACROSS ALL POTS
# ============================================
from collections import defaultdict

def count_continents(*pots):
    continent_count = defaultdict(int)
    for pot in pots:
        for team in pot:
            for cont in team["continent"]:
                continent_count[cont] += 1
    return dict(continent_count)

#test
#counts_all = count_continents(teams_pot1,teams_pot2,teams_pot3,teams_pot4)
#print(counts_all)

# ==========
# 7. Function -- Randomly draw a team from a pot.
# Input is the whole pot list, output is the team drawn(dict)
# After that, that pot will remove one team
# ==========
import random

def draw_one(team_list):

    # randomly pick an index
    idx = random.randrange(len(team_list))

      # get the dictionary at that index
    picked = team_list[idx]

      # remove it from the list
    team_list.pop(idx)

    return picked

#test
#picked_team = draw_one(teams_pot1)
#print(picked_team)
#print(teams_pot1)


# ==========
# 8.1 Function -- Put pot 1 team in the group.
# ==========
def place_team1(i,team_dict,group_list):
    #groups = [group.copy() for group in groups_original]
    group = group_list[i - 1]     # find group by label

    # 1. Put team name into THE FIRST spot (index 0)
    group["teams"][0] = team_dict["name"]

    # 2. Reduce the continent quota
    for cont in team_dict["continent"]:
        if cont in group:
            group[cont] -= 1

    return group_list

#test
#picked_team = draw_one(teams_pot1)
#pickone = place_team1(1,picked_team)
#print(pickone)
#counts_all = count_continents(teams_pot1,teams_pot2,teams_pot3,teams_pot4)
#print(counts_all)

# ==========
# 8.2 Function -- Put pot 2-4 team in the group.
# ==========

def place_team2to4(i, team_dict,group_list):
    #groups = [group.copy() for group in groups_original]
    group = group_list[i - 1]     # find group by label

    # 1. Find empty spots among index 1, 2, 3
    empty_positions = [idx for idx in range(1, 4) if group["teams"][idx] is None]

    # 2. Randomly choose one empty position
    pos = random.choice(empty_positions)

    # 3. Place the team
    group["teams"][pos] = team_dict["name"]

    # 4. Reduce continent quota
    for cont in team_dict["continent"]:
        if cont in group:
            group[cont] -= 1

    return group_list

#test


#print("\n".join(str(g) for g in groups))
#counts_all = count_continents(teams_pot1,teams_pot2,teams_pot3,teams_pot4)
#print(counts_all)

# ==========
# 8.3 Function -- Delete a team
# ==========


def remove_team(team_dict, groups):
    team_name = team_dict["name"]
    continents = team_dict["continent"]   # list, e.g. ["AFC", "CONCACAF", "CONMEBOL"]

    for group in groups:
        # Loop through the 4 team slots
        for i in range(len(group["teams"])):
            if group["teams"][i] == team_name:

                # Remove the team (set to None)
                group["teams"][i] = None

                # 🔥 Add back ALL continents
                for c in continents:
                    if c in group:
                        group[c] += 1

                return True  # Stop after finding it

    return False  # Not found

# ==========
# 9 Function -- Check whether there're multiple teams from the same continent
 #(more than 2 for UEFA)
# ==========


def check_continents(i, group_list):
    # Find the dictionary with label == i
    target = None
    for d in group_list:
        if d["label"] == i:
            target = d
            break

    if target is None:
        return False   # label not found

    # List of continent keys to check
    keys = ["UEFA", "AFC", "CAF", "CONCACAF", "CONMEBOL", "OFC"]

    # If any value is negative → return False
    for k in keys:
        if target[k] < 0:
            return False

    # Otherwise all non-negative → return True
    return True

#test


# ==========
# 9, Function -- Count empty groups
# ==========


def count_empty_teams(group_list):
    count = 0
    for g in group_list:
        # Check if all 4 slots are None
        if all(t is None for t in g["teams"]):
            count += 1
    return count

# ==========
# 10, Function -- Count whether remaining teams can form a good group
# =========

def check_continent_limits(n, continent_dict):
    # Extract UEFA
    uefa = continent_dict.get("UEFA", 0)


    other_keys = ["CAF", "AFC", "OFC", "CONMEBOL", "CONCACAF"]

    # Rule for UEFA: cannot be < n or > 2*n
    if uefa < n or uefa > 2 * n:
      #  print("剩余组欧洲过多或过少")
        return False

    # Other continents cannot be > n
    for key in other_keys:
        if continent_dict.get(key, 0) > n:
           # print("剩余组其他洲过多")
            return False

    # If all rules OK → return True + W
    return True




def check_empty_groups(groups):
    for g in groups:
        if all(t is None for t in g["teams"]):  # totally empty
            raise ValueError(f"Group {g['label']} is empty! Error triggered on purpose.")


# if counter > max_loops:
#   print("\n" * 50)



# ==========
# Last but 2, Function -- re-order the groups
# ==========

def reorder_groups(group_list):
    # Helper: find index of an item whose teams contain a keyword
    def find_index(keyword):
        for idx, item in enumerate(group_list):
            if any(keyword in str(team) for team in item["teams"]):
                return idx
        return None

    # 1. Move "Mexico" group to index 0
    idx_mex = find_index("Mexico")
    if idx_mex is not None and idx_mex != 0:
        group_list.insert(0, group_list.pop(idx_mex))

    # 2. Move "Canada" group to index 1
    idx_can = find_index("Canada")
    if idx_can is not None and idx_can != 1:
        group_list.insert(1, group_list.pop(idx_can))

    # 3. Move "USA" group to index 3
    idx_usa = find_index("USA")
    if idx_usa is not None and idx_usa != 3:
        group_list.insert(3, group_list.pop(idx_usa))

    return group_list

#group1= reorder_groups(groups)
# print(*group1,sep="\n")
# print("\n" * 80)


# ==========
# Find a team
# ==========

def find_team_group_index(groups_list, team_name):
    for idx, g in enumerate(groups_list):
        if team_name in g["teams"]:
            return idx    # return the index in groups_list
    return None  # team not found

#Spain=find_team_group_index(group1,"Spain")
#print(Spain)

# ==========
# Swap a team
# ==========

def swap_group_by_team(groups_list, team_name, target_index):
    # Step 1 — find current index of the team
    current_index = None
    for idx, group in enumerate(groups_list):
        if team_name in group["teams"]:
            current_index = idx
            break

    if current_index is None:
        raise ValueError(f"{team_name} not found in any group")

    # Step 2 — swap the whole group element
    groups_list[current_index], groups_list[target_index] = \
        groups_list[target_index], groups_list[current_index]

    return groups_list


def random_assignment_ABCD_list():
    # 4 lists (groups)
    lists = [
        [4, 5, 8],   # index 0 → top half
        [6, 7],      # index 1 → top half
        [2, 11],     # index 2 → bottom half
        [9, 10],     # index 3 → bottom half
    ]

    top = {0, 1}
    bottom = {2, 3}
    list_indices = [0, 1, 2, 3]

    valid_assignments = []

    # Permute the assignment of A,B,C,D to list indices
    for perm in itertools.permutations(list_indices, 4):
        A_list, B_list, C_list, D_list = perm

        # A and B must be in different halves
        cond_AB = ((A_list in top and B_list in bottom) or
                   (A_list in bottom and B_list in top))

        # C and D must be in different halves
        cond_CD = ((C_list in top and D_list in bottom) or
                   (C_list in bottom and D_list in top))

        if cond_AB and cond_CD:
            valid_assignments.append((A_list, B_list, C_list, D_list))

    # Pick one valid assignment
    A_list, B_list, C_list, D_list = random.choice(valid_assignments)

    # Choose one random number from each assigned list
    A_val = random.choice(lists[A_list])
    B_val = random.choice(lists[B_list])
    C_val = random.choice(lists[C_list])
    D_val = random.choice(lists[D_list])

    return [A_val, B_val, C_val, D_val]


# ==========
# Last Function -- print the groups
# ==========

def print_groups_only(group_list):
    # Group names A to L
    group_names = [chr(ord('A') + i) for i in range(12)]

    lines = []  # collect each group's text

    for idx, item in enumerate(group_list):
        teams_text = ", ".join([f'"{team}"' for team in item["teams"]])
        lines.append(f"Group {group_names[idx]}: {teams_text}")

    # Return one string with newline between each group
    return "\n".join(lines)

def extract_team_lists(group_list):
    return [item["teams"] for item in group_list]



def do_full_draw():

  # ==========
# 11, Test -- Add Iraq and DR Congo to group 1 and group 2. Add other teams as well
# =========
      # Create fresh copies for each draw
  global teams_pot1, teams_pot2, teams_pot3, teams_pot4, groups

  teams_pot1 = deepcopy(teams_pot1_original)
  teams_pot2 = deepcopy(teams_pot2_original)
  teams_pot3 = deepcopy(teams_pot3_original)
  teams_pot4 = deepcopy(teams_pot4_original)
  groups     = deepcopy(groups_original)
  place_team2to4(1,{"name": "Iraq/Bolivia/Suriname",  "continent": ["AFC","CONMEBOL","CONCACAF"]},groups)
  place_team2to4(2,{"name": "DR Congo/Jamaica/New Caledonia", "continent": ["CAF", "CONCACAF", "OFC"]},groups)

  for i in range(1,3):
    while True:
      p1 = draw_one(teams_pot1)
      place_team1(i,p1,groups)
      p2 = draw_one(teams_pot2)
      place_team2to4(i,p2,groups)
      p3 = draw_one(teams_pot3)
      place_team2to4(i,p3,groups)


      if check_continents(i,groups):
        break

      else:

        teams_pot1.append(p1)
        remove_team(p1,groups)
        teams_pot2.append(p2)
        remove_team(p2,groups)
        teams_pot3.append(p3)
        remove_team(p3,groups)

  #print(groups[0])
  #print(groups[1])
  #print("===")
  #print(count_continents(teams_pot1,teams_pot2,teams_pot3,teams_pot4))


  #print(*teams_pot2,sep="\n")
  counter = 0
  max_loops = 10000

  for i in range(3,13):
    if counter > max_loops:
    #  print("超时")
        break
    #print(i)
    while True:
        counter += 1
        if counter>max_loops:
          break
        p1 = draw_one(teams_pot1)
        place_team1(i,p1,groups)
        p2 = draw_one(teams_pot2)
        place_team2to4(i,p2,groups)
        p3 = draw_one(teams_pot3)
        place_team2to4(i,p3,groups)
        p4 = draw_one(teams_pot4)
        place_team2to4(i,p4,groups)

        empty = count_empty_teams(groups)
        summ = count_continents(teams_pot1,teams_pot2,teams_pot3,teams_pot4)

        if check_continents(i,groups) and check_continent_limits(empty,summ) and groups[i-1]["UEFA"]<2:
          break

        else:
          #print("re-draw")
          teams_pot1.append(p1)
          remove_team(p1,groups)
          teams_pot2.append(p2)
          remove_team(p2,groups)
          teams_pot3.append(p3)
          remove_team(p3,groups)
          teams_pot4.append(p4)
          remove_team(p4,groups)

  check_empty_groups(groups)
  random.shuffle(groups)
  group1= reorder_groups(groups)

  special = random_assignment_ABCD_list()
  #print(special)

  group2 = swap_group_by_team(group1, "🇪🇸Spain", special[0])
  # #print("group2:",*group2,sep="\n")
  group3 = swap_group_by_team(group2, "🇦🇷Argentina", special[1])
  # # # #print("group3:",*group2,sep="\n")
  group4 = swap_group_by_team(group3, "🇫🇷France", special[2])
  # # # #print("group4:",*group2,sep="\n")
  group5 = swap_group_by_team(group4, "🏴󠁧󠁢󠁥󠁮󠁧󠁿England", special[3])
  # # # #print("group5:",*group2,sep="\n")
  # # # #print(*group5,sep="\n")
  text = print_groups_only(group5)
  print(text)
  group6 = extract_team_lists(group5)
  #print(group6)
  return group6

def main():
    # all your World Cup draw logic here
    result = do_full_draw()
    return result

if __name__ == "__main__":
    main()